version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    ports:
      - 2181:2181
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc -w 2 zookeeper 2181" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - 9092:9092
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      - KAFKA_BROKE_ID=1001
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,PLAINTEXT_KAFKA://kafka:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_KAFKA:PLAINTEXT
    depends_on:
      zookeeper:
        condition: service_healthy

  postgres:
    image: postgres:9.6
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: popugword

  kafkaui:
    image: tchiotludo/akhq
    ports:
      - 8080:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "kafka:29092"

networks:
  default:
    name: popuga-network

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
  postgres-data:
